import "./globals.css";
import { Inter } from "next/font/google";
import { ThemeProvider } from "./utils/context/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rayen oueslati | Full stack developer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
